server:
  address: 127.0.0.1
  port: 8801
spring:
  application:
    name: pms-impl-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aB123!45C
    url: jdbc:mysql://localhost:3306/db_ys_kc?serverTimezone=UTC
#   dubbo:
#     application:
#       name: pms-impl-provider
#     registry:
#       address: zookeeper://127.0.0.1:2181
#     scan: com.ys.kc.cw.service
#zookeeper:

#  version=3.4.13
