server:
  address: 127.0.0.1
  port: 8802
spring:
  application:
    name: pms-controller
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aB123!45C
    url: jdbc:mysql://localhost:3306/db_ys_kc?serverTimezone=UTC
user:
  file:
    path: F:/img/
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.stdOutImpl